# Generated by Django 5.0.2 on 2024-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_category_slug_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='full_description',
            field=models.TextField(null=True),
        ),
    ]
